#!/data/data/com.termux/files/usr/bin/python
import os
print("this is created by Abhishek")
print("this command is used to install all the requirements package on termux")
os.system("apt-get update -y")
os.system("apt-get -y upgrade")
print("##########################")
print("follow the diploma all in 1 YouTube channel")
os.system("apt-get install -y ruby")
os.system("apt-get install -y perl")
print("############################")
os.system("apt-get install -y python2")
os.system("apt-get install -y nano")
print("subscribe the diploma all in 1 to get more videos")
print("#########################")
os.system("apt-get install -y wget")
os.system("apt-get install -y php")
os.system("apt-get install -y vim")
print("this is created by gpk group")
print("##########################")
os.system("apt-get install -y tar")
os.system("apt-get install -y zip")
os.system("apt-get install -y clang")
os.system("apt-get install -y nmap")
os.system("apt-get install -y macchanger")
print("#######################")
os.syatem("apt-get install -y jq")
os.system("apt-get install -y unzip")
os.system("apt-get install -y curl")
os.system("apt-get install -y tor")
os.system("apt-get install -y bmon")
print ("Rohit kumar mishra, suraj Kumar ranjan, suman kumar patel, rajnish raj, these are the also devloper of this script")
   print("subscribe my YouTube channel diploma all in 1")       
